robots:
  - name: "WidowX"
    type: "VX300S"
    obs_modalities: ["proprio"]
    proprio_obs: ["joint_qpos"]
    control_freq: 5
    dof: 8
    action_normalize: False
    action_type: "continuous"
    friction: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ] # TODO
    armature: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ] # TODO
    controller_name: "JointController"
    controller_config:
        arm_0:
            name: "JointController"
            "motor_type": "position"
            control_freq: 5
            use_delta_commands: False
            use_impedances: True
            use_gravity_compensation: False
            use_cc_compensation: False
            command_output_limits: "default"
            command_input_limits: "default"
            kp: 800
            damping_ratio: 0
        gripper_0:
          name: "MultiFingerGripperController"
          mode: "binary"

